<a href="https://colab.research.google.com/github/Nabaranjan/Numpy/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creating Numpy Arrays

In [ ]:
#np.array

import numpy as np

a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# 2D and 3D

b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3D

c = np.array([[[1,2],[3,4],[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [2]:
# data type
import numpy as np
np.array([1.,2.,3.])

array([1., 2., 3.])

In [3]:
# np.arange

np.arange(1,11)


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
# with reshape

np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
# np.ones and np.zeros

np.ones((3,4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [7]:
#np.random

np.random.random((3,4))

array([[0.04034967, 0.36020933, 0.29295033, 0.20491195],
       [0.65192122, 0.15824293, 0.22136759, 0.78997555],
       [0.64880228, 0.96382263, 0.98966473, 0.27110297]])

In [8]:
#np.linspace

np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [9]:
#np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [10]:
a1 = np.arange(10)
a2 =np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [11]:
# ndim

a3.ndim

3

In [12]:
# shape

a1.shape

(10,)

In [13]:
# size

a3.size

8

In [14]:
# itemsize

a3.itemsize

8

In [15]:
# dtype

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


In [3]:
# astype
import numpy as np
a1 = np.arange(10)
a2 =np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operations

In [4]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [5]:
# scalar operations

#arithmetic

a1 *+ 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [6]:
#relational

a1 > 5



array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [7]:
# vector operations
# arithmetic

a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [8]:
# Mean

np.mean(a1,axis=1)


array([1.5, 5.5, 9.5])