<a href="https://colab.research.google.com/github/Nabaranjan/Numpy/blob/main/Numpy_Tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#np.sort

In [1]:
#code
import numpy as np
a = np.random.randint(1, 100, 15)
a

array([88,  7, 51, 17, 19, 52,  4, 74, 46, 96, 51, 30, 32, 33, 39])

In [14]:
b = b = np.random.randint(1, 100, size=(6, 4))
print(b)

[[21 35 11 46]
 [ 6 75 65 33]
 [55 65 50 31]
 [20 91  5 84]
 [99 99 59 73]
 [48 88 99  8]]


In [15]:
np.sort(a)

array([ 4,  7, 17, 19, 30, 32, 33, 39, 46, 51, 51, 52, 74, 88, 96])

In [16]:
np.sort(b)

array([[11, 21, 35, 46],
       [ 6, 33, 65, 75],
       [31, 50, 55, 65],
       [ 5, 20, 84, 91],
       [59, 73, 99, 99],
       [ 8, 48, 88, 99]])

# np.append

In [18]:
#code
np.append(a,200)

array([ 88,   7,  51,  17,  19,  52,   4,  74,  46,  96,  51,  30,  32,
        33,  39, 200])

In [19]:
b

array([[21, 35, 11, 46],
       [ 6, 75, 65, 33],
       [55, 65, 50, 31],
       [20, 91,  5, 84],
       [99, 99, 59, 73],
       [48, 88, 99,  8]])

In [24]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[21., 35., 11., 46.,  1.],
       [ 6., 75., 65., 33.,  1.],
       [55., 65., 50., 31.,  1.],
       [20., 91.,  5., 84.,  1.],
       [99., 99., 59., 73.,  1.],
       [48., 88., 99.,  8.,  1.]])

In [25]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[21.        , 35.        , 11.        , 46.        ,  0.8197552 ],
       [ 6.        , 75.        , 65.        , 33.        ,  0.53449055],
       [55.        , 65.        , 50.        , 31.        ,  0.51069146],
       [20.        , 91.        ,  5.        , 84.        ,  0.55441427],
       [99.        , 99.        , 59.        , 73.        ,  0.77722132],
       [48.        , 88.        , 99.        ,  8.        ,  0.12108745]])

# np.concatenate

In [26]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [27]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique

In [29]:
#code

e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
f = np.array([[1,2,3,4],[1,2,3,2]])
print(e)
print(f)

[1 1 2 2 3 3 4 4 5 5 6 6]
[[1 2 3 4]
 [1 2 3 2]]


In [30]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims

In [31]:
# code
a

array([88,  7, 51, 17, 19, 52,  4, 74, 46, 96, 51, 30, 32, 33, 39])

In [32]:
a.shape

(15,)

In [34]:
np.expand_dims(a,axis=0)

array([[88,  7, 51, 17, 19, 52,  4, 74, 46, 96, 51, 30, 32, 33, 39]])

In [35]:
np.expand_dims(a,axis=0).shape

(1, 15)

# np.where

In [36]:
a

array([88,  7, 51, 17, 19, 52,  4, 74, 46, 96, 51, 30, 32, 33, 39])

In [37]:
# find all indices with value greater than 50

np.where(a>50)

(array([ 0,  2,  5,  7,  9, 10]),)

In [39]:
np.where(a>50,0,a)

array([ 0,  7,  0, 17, 19,  0,  4,  0, 46,  0,  0, 30, 32, 33, 39])

In [40]:
np.where(a%2 == 0,0,a)

array([ 0,  7, 51, 17, 19,  0,  0,  0,  0,  0, 51,  0,  0, 33, 39])

# np.argmax

In [42]:
# code
a

array([88,  7, 51, 17, 19, 52,  4, 74, 46, 96, 51, 30, 32, 33, 39])

In [43]:
np.argmax(a)

9

In [44]:
np.argmax(b,axis=0)

array([4, 4, 5, 3])

In [45]:
# np.argmin

np.argmin(a)

6

# np.cumsum

In [46]:
a

array([88,  7, 51, 17, 19, 52,  4, 74, 46, 96, 51, 30, 32, 33, 39])

In [47]:
np.cumsum(a)

array([ 88,  95, 146, 163, 182, 234, 238, 312, 358, 454, 505, 535, 567,
       600, 639])

In [48]:
# np.cumprod
np.cumprod(a)

array([                  88,                  616,                31416,
                     534072,             10147368,            527663136,
                 2110652544,         156188288256,        7184661259776,
            689727480938496,    35176101527863296,  1055283045835898880,
       -3124430680670339072,  7574251980136120320,   247922045955866624])

# np.percentile

In [49]:
a

array([88,  7, 51, 17, 19, 52,  4, 74, 46, 96, 51, 30, 32, 33, 39])

In [50]:
np.percentile(a,0)

4.0

In [51]:
np.percentile(a,50)

39.0

In [52]:
np.median(a)

39.0

# np.histogram

In [53]:
# code
a


array([88,  7, 51, 17, 19, 52,  4, 74, 46, 96, 51, 30, 32, 33, 39])

In [57]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])


(array([2, 2, 0, 4, 1, 3, 0, 1, 1, 1]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [58]:
np.histogram(a,bins=[0, 50, 100])

(array([9, 6]), array([  0,  50, 100]))

# np.corrcoef

In [59]:
salary = np.array([20000,40000,25000,35000,60000])
experience =np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin

In [60]:
a

array([88,  7, 51, 17, 19, 52,  4, 74, 46, 96, 51, 30, 32, 33, 39])

In [61]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([30])

# np.flip

In [62]:
a

array([88,  7, 51, 17, 19, 52,  4, 74, 46, 96, 51, 30, 32, 33, 39])

In [63]:
np.flip(a)

array([39, 33, 32, 30, 51, 96, 46, 74,  4, 52, 19, 17, 51,  7, 88])

In [64]:
b

array([[21, 35, 11, 46],
       [ 6, 75, 65, 33],
       [55, 65, 50, 31],
       [20, 91,  5, 84],
       [99, 99, 59, 73],
       [48, 88, 99,  8]])

In [65]:
np.flip(b)

array([[ 8, 99, 88, 48],
       [73, 59, 99, 99],
       [84,  5, 91, 20],
       [31, 50, 65, 55],
       [33, 65, 75,  6],
       [46, 11, 35, 21]])

# np.put

In [69]:
a

array([110, 530,  51,  17,  19,  52,   4,  74,  46,  96,  51,  30,  32,
        33,  39])

In [68]:
np.put(a,[0,1],[110,530])

# np.delete

In [70]:
a

array([110, 530,  51,  17,  19,  52,   4,  74,  46,  96,  51,  30,  32,
        33,  39])

In [73]:
np.delete(a,[0,1,2])

array([17, 19, 52,  4, 74, 46, 96, 51, 30, 32, 33, 39])

# Set Function



1.   np.union1d
2.   np.intersect1d
3.   np.setdiff1d
4.   np.setxor1d
5.   np.in1d






In [74]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [75]:
np.intersect1d(m,n)

array([3, 4, 5])

In [76]:
np.setdiff1d(m,n)

array([1, 2])

In [77]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [80]:
m[np.in1d(m,1)]

array([1])

# np.clip

In [81]:
a

array([110, 530,  51,  17,  19,  52,   4,  74,  46,  96,  51,  30,  32,
        33,  39])

In [82]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 51, 25, 25, 52, 25, 74, 46, 75, 51, 30, 32, 33, 39])